### ISSUE TITLE
Unable to get location for pointer Touch(0)

### ISSUE THREAD

**Issue by favilo** [aevyrie/bevy_mod_picking#316] opened 2024-02-27 07:55 UTC
I've been attempting to use the `Pointer<Up>` and `Pointer<Down>` events to handle touches on a mobile mancala game.

With the mouse, click events are working fine, but with touch input, I have to wait about 1 second for the `Pointer<Up>` event to be registered properly.

[Here is the code](https://github.com/favilo/stones/blob/main/src/game.rs#L336-L367) I'm attempting to use.

I can see the `Pointer<Down>` pretty much every time, but if I let go too early, I get the following error:

```Unable to get location for pointer Touch(0)```

Clearly this is happening in [pointer_events](https://github.com/aevyrie/bevy_mod_picking/blob/893336bf64265ee7d4bec2e1fefc16fb3e96e57a/crates/bevy_picking_core/src/events.rs#L251). But how can I ensure that the `PointerLocation` gets updated properly before the second is up?

**Comment by aevyrie** [comment] 2024-03-03 09:01
> but if I let go too early

My best guess is it's caused by bevy's lack of event ordering within a frame.

**Comment by Cyannide** [comment] 2024-05-06 14:32
AFAIK, this is fixed by #319

**Comment by aevyrie** [comment] 2024-06-12 06:35
Fixed by #319

**Closed by aevyrie** 2024-06-12 06:35 UTC
