### ISSUE TITLE
Mouse picking intersection doesn't update on camera move

### ISSUE THREAD

**Issue by Sheepyhead** [aevyrie/bevy_mod_picking#67] opened 2020-11-26 11:21 UTC
Hello, lovely plugin you have here! I was just implementing some simple movement in my game using this, and I ran into a minor issue. See I have a cube that has to move along a plane when a part of the plane's surface is clicked, and it's supposed to move to the point of the plane. The issue I'm facing is that the camera moves with it, and the intersection does not get updated unless I move the mouse, despite the fact that the mouse obviously intersects with the mesh in a different spot due to the new camera position. See attached gif for an example. 

I'm using the InteractableMesh and everything else works swimmingly, I figure this might be an oversight in how the InteractableMesh::mouse_down_event interacts with PickableMesh::intersection. 

I'm using version 0.2.0 so if this has already been fixed I apologize

![wMFEzTgViq (Custom) (2)](https://user-images.githubusercontent.com/15895891/100344720-8cb8cb00-2fe1-11eb-9dda-68e201f8a5a2.gif)

**Comment by aevyrie** [comment] 2020-11-27 06:36
Hey, thanks for the report! I'll have to see if this is happening in the debug cursor, or in the actual picking systems. I think the intent here is to only compute picks during a mouse movement, instead of running constantly. Some ways we could specify the always-on behavior:

1. In your world movement systems, send a callback to the picking system, letting it know it will need to run a check this frame because you've moved things around.
2. When setting up the `PickingSource`, there could be an "always-on" mode you specify.

Let me know if you have any thoughts on this! 🙂

**Comment by Sheepyhead** [comment] 2020-11-27 08:26
> 
> 
> Hey, thanks for the report! I'll have to see if this is happening in the debug cursor, or in the actual picking systems. I think the intent here is to only compute picks during a mouse movement, instead of running constantly. Some ways we could specify the always-on behavior:
> 
>     1. In your world movement systems, send a callback to the picking system, letting it know it will need to run a check this frame because you've moved things around.
> 
>     2. When setting up the `PickingSource`, there could be an "always-on" mode you specify.
> 
> 
> Let me know if you have any thoughts on this! 🙂

As shown in the example it also applies to the intersection returned by InteractableMesh, so the debug cursor is accurately showing the intersection it's returning. Now what I'd personally find most useful is to have a setting for PickingSource that it keeps updating the intersection even when a mouse button is held, personally I'd consider that the expected behavior, but leaving it as an option is fine

**Comment by aevyrie** [comment] 2020-12-12 19:24
I've been thinking about this a bit - I think you are completely right in that this should be default behavior. The plugin really doesn't work as intended if the scene isn't static.

1. By default, picking should update every frame any time the window is active (focused).
2. We can supply options for update behavior (always, while window focused, on mouse move, etc.) 

PR #68 gets us most of the way there. I will need to make some new test examples to verify this is working as intended.

**Comment by aevyrie** [comment] 2020-12-17 05:37
@Sheepyhead this is resolved in PR #78 and #68. Default behavior now results in picks being updated every frame for the cursor pick source. The 3d_scene example has been updated to show this new behavior by animating the camera.

**Closed by aevyrie** 2020-12-17 05:37 UTC
