### ISSUE TITLE
Use GlobalTransform for the PickSource

### ISSUE THREAD

**Issue by SarthakSingh31** [aevyrie/bevy_mod_picking#88] opened 2021-01-11 23:06 UTC
I have a `CameraRig` Entity and the `Camera` Entity (the pick source) is a child to it. So when I move my `CameraRig` the `GlobalTransform` of the `Camera` changes but not the `Transform`. This leads to wrong raycasts.

How to replicate:
1. Clone https://github.com/SarthakSingh31/bevy_4x_camera/tree/follow.
2. Run `cargo run --release`.
3. Move the camera forwards with `W`, keep the white moving box in view.
4. Try clicking on the white moving box after the camera has been moved forwards.

I tried changing [this](https://github.com/aevyrie/bevy_mod_picking/blob/c0934594328610a25978cd2d006523b2a160dc90/src/lib.rs#L257) `Transform` to `GlobalTransform` in a local copy and that fixes the issue.
I don't know if this is the best solution as a non-camera pick source might not have a `GlobalTransform` component.

**Comment by aevyrie** [comment] 2021-01-12 02:48
Yep, this looks like the correct way of doing this. I think this changed in Bevy 0.2-ish or something, but I don't use parenting so I haven't seen the regression.

**Comment by aevyrie** [comment] 2021-01-12 04:37
This is fixed in `0.3.5` 😁

**Closed by aevyrie** 2021-01-12 04:37 UTC
