### ISSUE TITLE
Possible memory leak?

### ISSUE THREAD

**Issue by intendednull** [aevyrie/bevy_mod_picking#109] opened 2021-11-23 03:11 UTC
Experiencing a memory leak on all web browsers (master branch). Removing the `PickableBundle` from my component fixes the issue. Any ideas or suggestions for debugging this?

**Comment by aevyrie** [comment] 2021-11-23 15:44
Do you see this when disabling the plugin outright? How severe is the leak?

**Comment by intendednull** [comment] 2021-11-23 21:34
@aevyrie yes, disabling the plugin also fixes the issue. The leak causes the browser to crash after a minute or so.

**Comment by aevyrie** [comment] 2022-01-16 07:21
I spent some time looking into this but was unable to replicate. On the Bevy discord, I saw some other discussions about OOM on wasm. I'll close this for now, but we can always reopen if we find any evidence that this is caused by this plugin.

**Closed by aevyrie** 2022-01-16 07:21 UTC
